
```{r}
library(data.table)
library(lattice)
library(ggplot2)
library(caret)
library(Momocs)
library(EBImage)

#import images
dir_images <- "~/Desktop/project3/images" #;dir_images
dir_names <- list.files(dir_images)#;dir_names
breed_name <- rep(NA, length(dir_names))

for(i in 1:length(dir_names)){
  tt <- unlist(strsplit(dir_names[i], "_"))
  tt <- tt[-length(tt)]
  breed_name[i] = paste(tt, collapse="_", sep="")
}

breed_name

cat_breed <- c("Abyssinian", "Bengal", "Birman", "Bombay", "British_Shorthair", "Egyptian_Mau","Maine_Coon", "Persian", "Ragdoll", "Russian_Blue", "Siamese", "Sphynx")

iscat <- breed_name %in% cat_breed;iscat
y_cat <- as.numeric(iscat)

#labels
#y_cat

#Split test and train data
set.seed(123)
trainindex <- createDataPartition(y_cat, p = .75, list = FALSE,times = 1)
trainname <- dir_names[trainindex]
testname <- dir_names[-trainindex]
trainlabel <- as.factor(y_cat[trainindex])
testlabel <- as.factor(y_cat[-trainindex])
```

```{r}
img_test_dir <- img_train_dir <- "~/Desktop/project3/images/"
#img_name <- testname
#img_dir <- "~/Desktop/project3/images/"

feature <- function(img_dir,img_name,data_name = NULL){

  n <- length(img_name)
  #n <- 50
  dat <- list()
  
  for(i in 1:n){
    
    if(trunc(i/5)*5==i){print(i)}
    #read images
    img <- readImage(paste0(img_dir,img_name)[i]) #;display(mat)
    img <- resize(img,128,128)
    
    # #High-pass Laplacian filtering
    # f_high <- matrix(1, nc=3, nr=3)
    # f_high[2,2] <- -8
    # img <- filter2(img, f_high)
    
    #Adaptive thresholding
    img <- channel(img, mode="gray") #;img
    img <- thresh(img, w = 60, h = 60, offset=0.05) #;display(img)
    img_2 <- opening(img, kern=makeBrush(11, shape='disc'))
    img_3 <- opening(img, kern=makeBrush(5, shape='disc'))
    img <- combine(img, img_2, img_3) #;display(img)
    
    # img <- resize(img,128,128)
    oc <- ocontour(bwlabel(img)) #;oc
    
    max <- c()
    for(j in 1:length(oc)){
     max[j] <- nrow(oc[[j]])
    }
    
    #max
    #plot(oc[[which.max(max)]], type='l')
    coo <- coo_sample(oc[[which.max(max)]], 50) #;coo
    #coo %>% coo_plot(points=TRUE)
    dat[[i]] <- coo
  }
  return(dat)
}

data_test <- feature(img_test_dir, testname)
data_test

```

